[package]
name = "anti302bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
url = "2.2.2"
reqwest = { version = "0.11.4", features = ["blocking"] }
teloxide = "0.3.1"